apiVersion: v2
name: istio-all
description: A Helm chart to insall all Istio Components, along with minimal kiali and prometheus in Kubernetes Cluster
type: application
version: 1.1.0
appVersion: "1.23.2"
kubeVersion: ">=1.27.0"
keywords:
  - istio 
  - istio-gateway
  - istio-cni
  - ztunnel
  - kiali-server
  - prometheus
  - Observability
  - Monitoring
  - service-mesh

icon: https://code4devs.github.io/logo.png
dependencies:
  - name: base
    version: 1.23.2
    repository: "https://istio-release.storage.googleapis.com/charts"
  - name: istiod
    version: 1.23.2
    repository: "https://istio-release.storage.googleapis.com/charts"
  - name: ztunnel
    version: 1.23.2
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: ztunnel.enabled
  - name: cni
    version: 1.23.2
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: cni.enabled
  - name: gateway
    alias: ingressgateway
    version: 1.23.2
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: ingressgateway.enabled
  - name: gateway
    alias: egressgateway
    version: 1.23.2
    repository: "https://istio-release.storage.googleapis.com/charts" 
    condition: egressgateway.enabled
  
  - name: kiali-server
    version: 1.89.3
    repository: "https://kiali.org/helm-charts"
    alias: kiali
    condition: kiali.enabled
  - name: prometheus
    version: 25.27.0
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled

annotations:
  artifacthub.io/category: "networking"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/license: "Apache-2.0"
  